### ISSUE TITLE
Type CKEditorModule does not have 'ɵmod' property.

### ISSUE THREAD

**Issue by AlanObject** [ckeditor/ckeditor5-angular#312]
My Angular components rendered into the browser, even though I do not have a `ckeditor` element in the view. I get the following Error traceback in the console:

```
core.mjs:1139 Uncaught Error: Type CKEditorModule does not have 'ɵmod' property.
    at getNgModuleDef (core.mjs:1139:1)
    at recurse (core.mjs:21757:1)
    at recurse (core.mjs:21768:1)
    at registerNgModuleType (core.mjs:21753:1)
    at new NgModuleFactory (core.mjs:21875:1)
    at compileNgModuleFactory (core.mjs:25895:1)
    at PlatformRef.bootstrapModule (core.mjs:26126:1)
    at Module.8835 (main.ts:11:26)
    at __webpack_require__ (bootstrap:19:1)
    at __webpack_exec__ (main.ts:12:37)
```

All that is required to re-create the problem is to bring up a simple application and import:

`import {CKEditorModule} from '@ckeditor/ckeditor5-angular';`

then

```
  import:
    CKEditorModule
```

I believe this is caused by the upgrade to Angular 13 but I have not had much luck in finding information on and understanding what the `emod` property is and how it is used.    Can anyone advise how to fix this?

Versions of things are:

```
Angular CLI: 13.2.6
Node: 16.14.0
Package Manager: npm 8.3.1
@angular-devkit/architect       0.1302.6
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            13.2.6
@angular-devkit/schematics      13.2.6
@angular/flex-layout            12.0.0-beta.34
@schematics/angular             13.2.6
rxjs                            6.6.7
typescript                      4.5.5
@ckeditor/ckeditor5-angular@4.0.0
```

**Comment by AlanObject** [comment]
I may have discovered the problem. This has to do with the changes related to importing modules. In my Angular component I used the following import statement:

`import * as Editor from '../../ckeditor5/build/ckeditor';`

change it to this:

`import * as Editor from '../../ckeditor5/build/ckeditor.js';`

and the problem seems to have resolved.

I would like to leave this issue open for a short while to see if anyone else has advice on this or if I come up with new information.

**Comment by AlanObject** [comment]
There doesn't seem to be any more to add to this issue except perhaps a suggestion to modify the documentation.

The conversion from CommonJS to ES Modules has a few bumps that every Javascript coder heeds to be aware of.  One really good web page I found on this is [here](https://electerious.medium.com/from-commonjs-to-es-modules-how-to-modernize-your-node-js-app-ad8cdd4fb662).   That is for node.js rather than the browser environment where CKEditor lives but it gives a good perspective.
