### ISSUE TITLE
destroy() doesn't work and throws an exception

### ISSUE THREAD

**Issue by TechwebCanadaPost** [ckeditor/ckeditor5-angular#334]
I used custom build of ckeditor5. Here are my codes:

```
import { CKEditorComponent, CKEditorModule } from '@ckeditor/ckeditor5-angular';
import * as CustomBuild from 'app/core/libs/ckeditor5/build/ckeditor';
....
....
@ViewChild( 'editor' ) editorComponent: CKEditorComponent;
public Editor = CustomBuild;
.....
......
  ngOnDestroy(): void {
    if(this.editorComponent.editorInstance)
    {
      this.editorComponent.editorInstance.destroy();
    }
  }
```

Here what I have in the html

`<ckeditor #editor [editor]="Editor" name="data1" [(ngModel)]="data1"></ckeditor>`

When the component is destroyed, here is the bug I have

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'attributes')
TypeError: Cannot read properties of undefined (reading 'attributes')
    at Ef.detachDomRoot (universalModuleDefinition:1:1)
    at cx.destroy (universalModuleDefinition:1:1)
    at nW.destroy (universalModuleDefinition:1:1)
    at CKEditorComponent.<anonymous> (ckeditor-ckeditor5-angular.js:266:1)
    at Generator.next (<anonymous>)
    at tslib.es6.js:76:1
    at new ZoneAwarePromise (zone.js:1387:1)
    at __awaiter (tslib.es6.js:72:1)
    at EditorWatchdog.destructor [as _destructor] (ckeditor-ckeditor5-angular.js:265:49)
    at editorwatchdog.js:243:1
    at resolvePromise (zone.js:1213:1)
    at zone.js:1120:1
    at rejected (tslib.es6.js:74:89)
    at ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.mjs:25877:33)
    at ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1276:1
    at ZoneDelegate.invokeTask (zone.js:406:1)
    at Object.onInvokeTask (core.mjs:25864:33)
```
The error happens with  this.editorComponent.editorInstance.destroy(); 

I have used the editor as a nested component but have no luck.

**Comment by mabryl** [comment]
Hello @surfme,

Thanks for reaching out. I tried recreating your issue on my end but I wasn't successful. I followed [this tutorial](https://www.notion.so/Benefits-3ab3de08dcd44e62bea7239c653f31a7) available in our docs to create an Angular app integrated with our editor and the `onDestroy` hook didn't throw any errors for me.

But perhaps our implementations of the editor differ, so could you describe how CKE is integrated with your app? Do you have a separate component that houses the editor and you then import it into your main App.js file?

Also, there's [this section](https://ckeditor.com/docs/ckeditor5/latest/installation/frameworks/angular.html#common-issues) in our docs that describes a known issue with the onDestroy hook. Perhaps you'll find it helpful in your debugging.

Please let me know whether you found this information useful. If not, please provide more details about your implementation and we'll debug further.

**Comment by pomek** [comment]
Closing due to lack of activity. If you think the issue is still not resolved, please, re-open it and provide the feedback we asked for.
